_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 256
buffer_alpha:
    value: 0.3
buffer_beta:
    value: 0.9
buffer_capacity:
    value: 30000
epsilon_decay_prop:
    value: 0.7
gamma:
    value: 0.99
lr:
    value: 1e-05
max_grad_norm:
    value: 1
soft_tau:
    value: 0.01
