wandb_version: 1

batch_size:
  value: 512
buffer_alpha:
  value: 0.7
buffer_beta:
  value: 0.7
buffer_capacity:
  value: 30000
epsilon_decay_prop:
  value: 0.9
gamma:
  value: 0.98
lr:
  value: 0.0001
max_grad_norm:
  value: 0.5
soft_tau:
  value: 0.01
