wandb_version: 1

batch_size:
  value: 512
buffer_alpha:
  value: 0.3
buffer_beta:
  value: 0.6
buffer_capacity:
  value: 10000
epsilon_decay_prop:
  value: 0.9
gamma:
  value: 0.99
lr:
  value: 1.0e-05
max_grad_norm:
  value: 1
soft_tau:
  value: 0.1
