wandb_version: 1

batch_size:
  value: 256
buffer_alpha:
  value: 0.7
buffer_beta:
  value: 0.8
buffer_capacity:
  value: 20000
epsilon_decay_prop:
  value: 0.7
gamma:
  value: 0.98
lr:
  value: 1.0e-05
max_grad_norm:
  value: 1
soft_tau:
  value: 0.1
